Pinning pymongo version to 3.6.0
The lastest version (3.8.0) breaks importing common.

{\"exc_message\":\"cannot import name common\",\"exc_type\":\"ImportError\",\"stack_trace\":\"Traceback (most recent call last):
  File \\\"/executor.py\\\", line 12, in execute
    from flexer.context import FlexerContext, FlexerRemoteState
  File \\\"/libs/dist-packages/flexer/context.py\\\", line 4, in \\u003cmodule\\u003e
    import pymongo
  File \\\"/libs/dist-packages/pymongo/__init__.py\\\", line 77, in \\u003cmodule\\u003e
    from pymongo.collection import ReturnDocument
  File \\\"/libs/dist-packages/pymongo/collection.py\\\", line 29, in \\u003cmodule\\u003e
    from pymongo import (common,
ImportError: cannot import name common
\"}